FAPI = FAPI()
nv_created = FAPI.create_nv(path=b"/NV/my_storage", size=32, type_="bitfield", policy_path=b"/policy/my_policy", auth_value=b"my_password", exists_ok=True)
print("NV created: " + nv_created)
FAPI.nv_write(path=b"/NV/my_storage", data=b"my_secret_master_key_here")
FAPI.close()
